// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class Garden
    {
        public Garden()
        {
            GardenSensors = new HashSet<GardenSensor>();
            Plants = new HashSet<Plant>();
            Users = new HashSet<User>();
        }

        public string IdGarden { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Watered { get; set; }
        public DateTime? LastWatered { get; set; }
        public DateTime? WateringDuration { get; set; }

        public virtual ICollection<GardenSensor> GardenSensors { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}