// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class Garden
    {
        public Garden()
        {
            GardenSensors = new HashSet<GardenSensor>();
        }

        public string IdGarden { get; set; }
        public string Name { get; set; }
        public short? Watered { get; set; }
        public DateTime? LastWatered { get; set; }
        public int? IdPlant { get; set; }
        public int? IdUser { get; set; }
        public int? WateringDuration { get; set; }

        public virtual Plant IdPlantNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual ICollection<GardenSensor> GardenSensors { get; set; }
    }
}