// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class Plant
    {
        public Plant()
        {
            Gardens = new HashSet<Garden>();
        }

        public int IdPlant { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public double? OptimalTemperature { get; set; }
        public double? SoilMoisture { get; set; }
        public double? AirMoisture { get; set; }
        public double? Light { get; set; }

        public virtual ICollection<Garden> Gardens { get; set; }
    }
}