// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class Plant
    {
        public string IdPlant { get; set; }
        public string IdGarden { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public DateTime? WateringInterval { get; set; }

        public virtual Garden IdGardenNavigation { get; set; }
    }
}