// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class User
    {
        public User()
        {
            Gardens = new HashSet<Garden>();
        }

        public int IdUser { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Role { get; set; }

        public virtual ICollection<Garden> Gardens { get; set; }
    }
}