// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iGardenConnectAPI.Models
{
    public partial class Garden
    {
        public Garden()
        {
            GardenSensor = new HashSet<GardenSensor>();
        }

        public string IdGarden { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public DateTime? WateringDuration { get; set; }
        public short? Watered { get; set; }
        public DateTime? LastWatered { get; set; }
        public string IdPlant { get; set; }
        public string IdUser { get; set; }

        public virtual Plant IdPlantNavigation { get; set; }
        public virtual User IdUserNavigation { get; set; }
        public virtual ICollection<GardenSensor> GardenSensor { get; set; }
    }
}