// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iGardenConnectAPI.Models
{
    public partial class Sensor
    {
        public Sensor()
        {
            GardenSensor = new HashSet<GardenSensor>();
        }

        public string IdSensor { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Price { get; set; }

        public virtual ICollection<GardenSensor> GardenSensor { get; set; }
    }
}